<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'locales' => 'get5bdb55f55593f291191610',
  'Middlewares\\ContentLanguage' => 'get5bdb55f5559c5039686179',
  'SubEntry5bdb55f555ea9' => 'get5bdb55f555ebe300410364',
  'oauth.private_key' => 'get5bdb55f555f95168501026',
  'oauth.public_key' => 'get5bdb55f5653f3851777334',
  'oauth.encryption_key' => 'get5bdb55f56a5bb245183340',
  'oauth.access_token.lifetime' => 'get5bdb55f56f7f8881564465',
  'oauth.auth_code.lifetime' => 'get5bdb55f5748a7289679789',
  'oauth.refresh_token.lifetime' => 'get5bdb55f57994c458552394',
  'League\\OAuth2\\Server\\ResourceServer' => 'get5bdb55f57ea2e416508487',
  'SubEntry5bdb55f57ea60' => 'get5bdb55f57ea68697084710',
  'SubEntry5bdb55f57ea80' => 'get5bdb55f57ea85463314622',
  'League\\OAuth2\\Server\\AuthorizationServer' => 'get5bdb55f57eab4846761497',
  'SubEntry5bdb55f57eadc' => 'get5bdb55f57eae3168161782',
  'SubEntry5bdb55f57eaf7' => 'get5bdb55f57eafc001342940',
  'SubEntry5bdb55f57eb0e' => 'get5bdb55f57eb13123583751',
  'SubEntry5bdb55f57eb24' => 'get5bdb55f57eb29929823480',
  'SubEntry5bdb55f57eb3a' => 'get5bdb55f57eb40879961868',
  'SubEntry5bdb55f57eb70' => 'get5bdb55f57eb76561242422',
  'SubEntry5bdb55f57eb88' => 'get5bdb55f57eb8d117735842',
  'SubEntry5bdb55f57ebad' => 'get5bdb55f57ebb3332780541',
  'SubEntry5bdb55f57ebc4' => 'get5bdb55f57ebc9101703023',
  'League\\OAuth2\\Server\\Grant\\AuthCodeGrant' => 'get5bdb55f57ebe8005632410',
  'SubEntry5bdb55f57ec09' => 'get5bdb55f57ec0f360366930',
  'SubEntry5bdb55f57ec22' => 'get5bdb55f57ec27187262127',
  'SubEntry5bdb55f57ec39' => 'get5bdb55f57ec3e520349210',
  'SubEntry5bdb55f57ec62' => 'get5bdb55f57ec68002633371',
  'League\\OAuth2\\Server\\Grant\\RefreshTokenGrant' => 'get5bdb55f57ec87265969005',
  'SubEntry5bdb55f57eca5' => 'get5bdb55f57ecab054290301',
  'SubEntry5bdb55f57ecd1' => 'get5bdb55f57ecd7302349462',
  'League\\Plates\\Engine' => 'get5bdb55f57ecf6008431236',
  'SubEntry5bdb55f57ed14' => 'get5bdb55f57ed1a663221280',
  'SubEntry5bdb55f57ed2e' => 'get5bdb55f57ed33086599207',
  'SubEntry5bdb55f57ed58' => 'get5bdb55f57ed5e320160190',
  'SubEntry5bdb55f57ed7c' => 'get5bdb55f57ed82092276466',
  'Sherpa\\Plates\\PlateExtension\\AppExtension' => 'get5bdb55f57eda1713473651',
  'SubEntry5bdb55f57edc0' => 'get5bdb55f57edc6970077535',
  'SubEntry5bdb55f57edd9' => 'get5bdb55f57edde936688056',
  'renderer.engine' => 'get5bdb55f57ee00896448666',
  'renderer.dir' => 'get5bdb55f57ee13284335896',
  'renderer.ext' => 'get5bdb55f57ee31290803302',
  'Aura\\Router\\Generator' => 'get5bdb55f57ee44103758016',
  'doctrine.config' => 'get5bdb55f5826b2553669857',
  'Doctrine\\ORM\\EntityManagerInterface' => 'get5bdb55f584af4748861742',
  'doctrine.entity_folders' => 'get5bdb55f586e5e258281566',
  'doctrine.manager' => 'get5bdb55f5891c5523689309',
  'doctrine.connection' => 'get5bdb55f5891df026995246',
  'doctrine.connection.url' => 'get5bdb55f58b3d2741578238',
  'project.root' => 'get5bdb55f58b3fd819036802',
  'project.cache' => 'get5bdb55f58b411781915320',
  'project.src' => 'get5bdb55f58b42b470282969',
  'project.namespace' => 'get5bdb55f58b446286976950',
  'error.handler' => 'get5bdb55f58b458344596271',
  'response.emitter' => 'get5bdb55f58eb9b684531748',
  'Sherpa\\App\\App' => 'get5bdb55f59203c095908569',
  'base_path' => 'get5bdb55f59205b681618218',
  'debug' => 'get5bdb55f592071793792089',
  'App\\Repository\\AccessTokenRepository' => 'get5bdb55f592273347483483',
  'SubEntry5bdb55f592299' => 'get5bdb55f5922a1955282420',
  'App\\Repository\\ClientRepository' => 'get5bdb55f59237a013676115',
  'SubEntry5bdb55f59239c' => 'get5bdb55f5923a4302659346',
  'App\\Repository\\ScopeRepository' => 'get5bdb55f592479948493474',
  'SubEntry5bdb55f59249b' => 'get5bdb55f5924a3961577448',
  'App\\Repository\\AuthCodeRepository' => 'get5bdb55f592573819356349',
  'SubEntry5bdb55f592594' => 'get5bdb55f59259c310176734',
  'App\\Repository\\RefreshTokenRepository' => 'get5bdb55f59266e579599292',
  'SubEntry5bdb55f59268f' => 'get5bdb55f592697962821648',
  'Sherpa\\Plates\\PlateExtension\\HelperExtension' => 'get5bdb55f592831748610008',
);

    protected function get5bdb55f55593f291191610()
    {
        return [
            0 => 'en',
            1 => 'fr',
        ];
    }

    protected function get5bdb55f555ebe300410364()
    {
        return $this->delegateContainer->get('locales');
    }

    protected function get5bdb55f5559c5039686179()
    {
        $object = new Middlewares\ContentLanguage($this->get5bdb55f555ebe300410364(), NULL);
        $object->usePath(true);
        return $object;
    }

    protected function get5bdb55f555f95168501026()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $container) {
    return file_get_contents($container->get('project.root') . '/private.key');
}, 'oauth.private_key');
    }

    protected function get5bdb55f5653f3851777334()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $container) {
    return file_get_contents($container->get('project.root') . '/public.key');
}, 'oauth.public_key');
    }

    protected function get5bdb55f56a5bb245183340()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $container) {
    return \Defuse\Crypto\Key::loadFromAsciiSafeString(file_get_contents($container->get('project.root') . '/diffuse.key'));
}, 'oauth.encryption_key');
    }

    protected function get5bdb55f56f7f8881564465()
    {
        return $this->resolveFactory(static function () {
    return new \DateInterval('PT1H');
}, 'oauth.access_token.lifetime');
    }

    protected function get5bdb55f5748a7289679789()
    {
        return $this->resolveFactory(static function () {
    return new \DateInterval('PT10M');
}, 'oauth.auth_code.lifetime');
    }

    protected function get5bdb55f57994c458552394()
    {
        return $this->resolveFactory(static function () {
    return new \DateInterval('P1M');
}, 'oauth.refresh_token.lifetime');
    }

    protected function get5bdb55f57ea68697084710()
    {
        return $this->delegateContainer->get('App\\Repository\\AccessTokenRepository');
    }

    protected function get5bdb55f57ea85463314622()
    {
        return $this->delegateContainer->get('oauth.public_key');
    }

    protected function get5bdb55f57ea2e416508487()
    {
        $object = new League\OAuth2\Server\ResourceServer($this->get5bdb55f57ea68697084710(), $this->get5bdb55f57ea85463314622(), NULL);
        return $object;
    }

    protected function get5bdb55f57eae3168161782()
    {
        return $this->delegateContainer->get('App\\Repository\\ClientRepository');
    }

    protected function get5bdb55f57eafc001342940()
    {
        return $this->delegateContainer->get('App\\Repository\\AccessTokenRepository');
    }

    protected function get5bdb55f57eb13123583751()
    {
        return $this->delegateContainer->get('App\\Repository\\ScopeRepository');
    }

    protected function get5bdb55f57eb29929823480()
    {
        return $this->delegateContainer->get('oauth.private_key');
    }

    protected function get5bdb55f57eb40879961868()
    {
        return $this->delegateContainer->get('oauth.encryption_key');
    }

    protected function get5bdb55f57eb76561242422()
    {
        return $this->delegateContainer->get('League\\OAuth2\\Server\\Grant\\AuthCodeGrant');
    }

    protected function get5bdb55f57eb8d117735842()
    {
        return $this->delegateContainer->get('oauth.access_token.lifetime');
    }

    protected function get5bdb55f57ebb3332780541()
    {
        return $this->delegateContainer->get('League\\OAuth2\\Server\\Grant\\RefreshTokenGrant');
    }

    protected function get5bdb55f57ebc9101703023()
    {
        return $this->delegateContainer->get('oauth.access_token.lifetime');
    }

    protected function get5bdb55f57eab4846761497()
    {
        $object = new League\OAuth2\Server\AuthorizationServer($this->get5bdb55f57eae3168161782(), $this->get5bdb55f57eafc001342940(), $this->get5bdb55f57eb13123583751(), $this->get5bdb55f57eb29929823480(), $this->get5bdb55f57eb40879961868(), NULL);
        $object->enableGrantType($this->get5bdb55f57eb76561242422(), $this->get5bdb55f57eb8d117735842());
        $object->enableGrantType($this->get5bdb55f57ebb3332780541(), $this->get5bdb55f57ebc9101703023());
        return $object;
    }

    protected function get5bdb55f57ec0f360366930()
    {
        return $this->delegateContainer->get('App\\Repository\\AuthCodeRepository');
    }

    protected function get5bdb55f57ec27187262127()
    {
        return $this->delegateContainer->get('App\\Repository\\RefreshTokenRepository');
    }

    protected function get5bdb55f57ec3e520349210()
    {
        return $this->delegateContainer->get('oauth.auth_code.lifetime');
    }

    protected function get5bdb55f57ec68002633371()
    {
        return $this->delegateContainer->get('oauth.refresh_token.lifetime');
    }

    protected function get5bdb55f57ebe8005632410()
    {
        $object = new League\OAuth2\Server\Grant\AuthCodeGrant($this->get5bdb55f57ec0f360366930(), $this->get5bdb55f57ec27187262127(), $this->get5bdb55f57ec3e520349210());
        $object->setRefreshTokenTTL($this->get5bdb55f57ec68002633371());
        return $object;
    }

    protected function get5bdb55f57ecab054290301()
    {
        return $this->delegateContainer->get('App\\Repository\\RefreshTokenRepository');
    }

    protected function get5bdb55f57ecd7302349462()
    {
        return $this->delegateContainer->get('oauth.refresh_token.lifetime');
    }

    protected function get5bdb55f57ec87265969005()
    {
        $object = new League\OAuth2\Server\Grant\RefreshTokenGrant($this->get5bdb55f57ecab054290301());
        $object->setRefreshTokenTTL($this->get5bdb55f57ecd7302349462());
        return $object;
    }

    protected function get5bdb55f57ed1a663221280()
    {
        return $this->delegateContainer->get('renderer.dir');
    }

    protected function get5bdb55f57ed33086599207()
    {
        return $this->delegateContainer->get('renderer.ext');
    }

    protected function get5bdb55f57ed5e320160190()
    {
        return $this->delegateContainer->get('Sherpa\\Plates\\PlateExtension\\AppExtension');
    }

    protected function get5bdb55f57ed82092276466()
    {
        return $this->delegateContainer->get('Sherpa\\Plates\\PlateExtension\\HelperExtension');
    }

    protected function get5bdb55f57ecf6008431236()
    {
        $object = new League\Plates\Engine($this->get5bdb55f57ed1a663221280(), $this->get5bdb55f57ed33086599207());
        $object->loadExtension($this->get5bdb55f57ed5e320160190());
        $object->loadExtension($this->get5bdb55f57ed82092276466());
        return $object;
    }

    protected function get5bdb55f57edc6970077535()
    {
        return $this->delegateContainer->get('Psr\\Http\\Message\\ServerRequestInterface');
    }

    protected function get5bdb55f57edde936688056()
    {
        return $this->delegateContainer->get('router');
    }

    protected function get5bdb55f57eda1713473651()
    {
        $object = new Sherpa\Plates\PlateExtension\AppExtension($this->get5bdb55f57edc6970077535(), $this->get5bdb55f57edde936688056());
        return $object;
    }

    protected function get5bdb55f57ee00896448666()
    {
        return $this->delegateContainer->get('League\\Plates\\Engine');
    }

    protected function get5bdb55f57ee13284335896()
    {
        return \DI\Definition\StringDefinition::resolveExpression('renderer.dir', '{project.root}/templates', $this->delegateContainer);
    }

    protected function get5bdb55f57ee31290803302()
    {
        return 'php';
    }

    protected function get5bdb55f57ee44103758016()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $container) {
    return $container->get('router')->getGenerator();
}, 'Aura\\Router\\Generator');
    }

    protected function get5bdb55f5826b2553669857()
    {
        return $this->resolveFactory(static function (\DI\Container $container) {
    return \Doctrine\ORM\Tools\Setup::createAnnotationMetadataConfiguration($container->get('doctrine.entity_folders'), $container->get('debug'));
}, 'doctrine.config');
    }

    protected function get5bdb55f584af4748861742()
    {
        return $this->resolveFactory(static function (\DI\Container $container) {
    return \Doctrine\ORM\EntityManager::create($container->get('doctrine.connection'), $container->get('doctrine.config'));
}, 'Doctrine\\ORM\\EntityManagerInterface');
    }

    protected function get5bdb55f586e5e258281566()
    {
        return $this->resolveFactory(static function (\DI\Container $container) {
    return [$container->get('project.src') . "/Entity"];
}, 'doctrine.entity_folders');
    }

    protected function get5bdb55f5891c5523689309()
    {
        return $this->delegateContainer->get('Doctrine\\ORM\\EntityManagerInterface');
    }

    protected function get5bdb55f5891df026995246()
    {
        return $this->resolveFactory(static function (\DI\Container $container) {
    return ['url' => $container->get('doctrine.connection.url')];
}, 'doctrine.connection');
    }

    protected function get5bdb55f58b3d2741578238()
    {
                $value = getenv('DATABASE_URL');
        if (false !== $value) return $value;
        if (!false) {
            throw new \DI\Definition\Exception\InvalidDefinition("The environment variable 'DATABASE_URL' has not been defined");
        }
        return NULL;
    }

    protected function get5bdb55f58b3fd819036802()
    {
        return '/var/www/html/hyperdoc/api';
    }

    protected function get5bdb55f58b411781915320()
    {
        return \DI\Definition\StringDefinition::resolveExpression('project.cache', '{project.root}/var/cache', $this->delegateContainer);
    }

    protected function get5bdb55f58b42b470282969()
    {
        return \DI\Definition\StringDefinition::resolveExpression('project.src', '{project.root}/src', $this->delegateContainer);
    }

    protected function get5bdb55f58b446286976950()
    {
        return 'App\\';
    }

    protected function get5bdb55f58b458344596271()
    {
        return $this->resolveFactory(static function () {
    return new \Middlewares\ErrorHandlerDefault();
}, 'error.handler');
    }

    protected function get5bdb55f58eb9b684531748()
    {
        return $this->resolveFactory(static function () {
    return new \Zend\Diactoros\Response\SapiEmitter();
}, 'response.emitter');
    }

    protected function get5bdb55f59203c095908569()
    {
        return $this->delegateContainer->get('Sherpa\\App\\App');
    }

    protected function get5bdb55f59205b681618218()
    {
        return '/hyperdoc/api/public';
    }

    protected function get5bdb55f592071793792089()
    {
        return false;
    }

    protected function get5bdb55f5922a1955282420()
    {
        return $this->delegateContainer->get('Doctrine\\ORM\\EntityManagerInterface');
    }

    protected function get5bdb55f592273347483483()
    {
        $object = new App\Repository\AccessTokenRepository($this->get5bdb55f5922a1955282420());
        return $object;
    }

    protected function get5bdb55f5923a4302659346()
    {
        return $this->delegateContainer->get('Doctrine\\ORM\\EntityManagerInterface');
    }

    protected function get5bdb55f59237a013676115()
    {
        $object = new App\Repository\ClientRepository($this->get5bdb55f5923a4302659346());
        return $object;
    }

    protected function get5bdb55f5924a3961577448()
    {
        return $this->delegateContainer->get('Doctrine\\ORM\\EntityManagerInterface');
    }

    protected function get5bdb55f592479948493474()
    {
        $object = new App\Repository\ScopeRepository($this->get5bdb55f5924a3961577448());
        return $object;
    }

    protected function get5bdb55f59259c310176734()
    {
        return $this->delegateContainer->get('Doctrine\\ORM\\EntityManagerInterface');
    }

    protected function get5bdb55f592573819356349()
    {
        $object = new App\Repository\AuthCodeRepository($this->get5bdb55f59259c310176734());
        return $object;
    }

    protected function get5bdb55f592697962821648()
    {
        return $this->delegateContainer->get('Doctrine\\ORM\\EntityManagerInterface');
    }

    protected function get5bdb55f59266e579599292()
    {
        $object = new App\Repository\RefreshTokenRepository($this->get5bdb55f592697962821648());
        return $object;
    }

    protected function get5bdb55f592831748610008()
    {
        $object = new Sherpa\Plates\PlateExtension\HelperExtension();
        return $object;
    }

}
